/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AceEditor: typeof import('./src/components/Editor/AceEditor.vue')['default']
    ComponentList: typeof import('./src/components/ComponentList.vue')['default']
    ComponentWrapper: typeof import('./src/components/Editor/ComponentWrapper.vue')['default']
    copy: typeof import('./src/components/Editor/index copy.vue')['default']
    Editor: typeof import('./src/components/Editor/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    Grid: typeof import('./src/components/Editor/Grid.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IEpCircleCheckFilled: typeof import('~icons/ep/circle-check-filled')['default']
    IEpPlus: typeof import('~icons/ep/plus')['default']
    Preview: typeof import('./src/components/Editor/Preview.vue')['default']
    RealTimeComponentList: typeof import('./src/components/RealTimeComponentList.vue')['default']
    Shape: typeof import('./src/components/Editor/Shape.vue')['default']
    ToolBar: typeof import('./src/components/ToolBar.vue')['default']
  }
}
